apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 10Gi # Increase the storage capacity as per your requirements
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2 # Change the storage class name to "gp2" for EBS
  persistentVolumeReclaimPolicy: Retain # This will retain the EBS volume when the pod is deleted
  awsElasticBlockStore:
    volumeID: vol-014bcf4bd55329622 # Replace this with the EBS volume ID that you want to use
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  resources:
    requests:
      storage: 10Gi # Increase the storage capacity as per your requirements
  storageClassName: gp2 # Change the storage class name to "gp2" for EBS
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /var/lib/mongodb
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
