apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  
spec:
  selector:
    matchLabels:
      app: eureka # has to match .spec.template.metadata.labels
  serviceName: "eureka"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: eureka # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: eureka
        image: eureka-slim:1.16.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  
spec:
  selector:
    app: eureka
  clusterIP: None
  # sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: eureka
    protocol: TCP
    port: 8761

    # targetPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
  
spec:
  selector:
    app: eureka
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - port: 80
    targetPort: 8761
  

  